from enum import Enum


class Interest(str, Enum):
    FRIENDS = "FRIENDS"
    FUN = "FUN"
    MOVEMENT = "MOVEMENT"
    CAREER = "CAREER"
    LEARNING = "LEARNING"
    CREATIVITY = "CREATIVITY"
    EXPLORATION = "EXPLORATION"
    HOME = "HOME"
    REST = "REST"
    PERSONAL_PROJECTS = "PERSONAL_PROJECTS"
    NEW_EXPERIENCES = "NEW_EXPERIENCES"
